# 线性代数

## 数在空间的放置：标量、向量、矩阵、张量

标量(scalar)是一个单独的数。

In [5]:
import numpy as np
x_scalar = 1
print('x_scalar is {}'.format(x_scalar))
type(x_scalar)

x_scalar is 1


int

向量(vector)是一列数。

In [21]:
x_vector = np.array([1,2,3])
print('x_vector is {}'.format(x_vector))
print('type is {}'.format(type(x_vector)))
print('shape is {}'.format(x_vector.shape))
print('T shape is {}'.format(x_vector.T.shape)) # 从这里看，numpy的1维数组，是不分行向量和列向量的

x_vector is [1 2 3]
type is <class 'numpy.ndarray'>
shape is (3,)
T shape is (3,)


矩阵(matrix)是一个二维数组。

In [24]:
x_matrix = np.array([[1,2,3],[4,5,6]])
print('x_matrix is {}'.format(x_matrix))
print('x_matrix shape is {}'.format(x_matrix.shape))

x_matrix is [[1 2 3]
 [4 5 6]]
x_matrix shape is (2, 3)


张量(tensor)是超过二维的数组。

In [29]:
x_tensor = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print('x_tensor shape is {}'.format(x_tensor.shape))
x_tensor

x_tensor shape is (2, 3, 4)


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

## 运算

### 矩阵乘法

In [39]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
c = np.dot(a,b)
print('a is \n{}'.format(a))
print('b is \n{}'.format(b))
c

a is 
[[1 2]
 [3 4]]
b is 
[[1 2]
 [3 4]]


array([[ 7, 10],
       [15, 22]])

In [44]:
x = np.array([1,2,3])
y = np.array([[1,2,3],[4,5,6]])
z = np.dot(y,x) # x被视为列向量
z

array([14, 32])

In [49]:
x2 = np.array([1,2])
z2 = np.dot(x2,y) # x2被视为行向量
z2

array([ 9, 12, 15])

### 元素乘

In [38]:
d = a * b
d

array([[ 1,  4],
       [ 9, 16]])

### 标量运算

In [50]:
a

array([[1, 2],
       [3, 4]])

In [52]:
a1 = a + 1
a1

array([[2, 3],
       [4, 5]])

In [56]:
a2 = a * 2
a2

array([[2, 4],
       [6, 8]])

In [59]:
a3 = a ** 2
a3

array([[ 1,  4],
       [ 9, 16]])

### 转置

In [60]:
a

array([[1, 2],
       [3, 4]])

In [61]:
a.T

array([[1, 3],
       [2, 4]])

### 矩阵的逆矩阵

$A A^{-1} = I$，其中$I$是单位矩阵，$A^{-1}$是矩阵的逆矩阵。

In [65]:
A = np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)
print('inv is {}'.format(A_inv))
print('dot is {}'.format(np.dot(A, A_inv)))

inv is [[-2.   1. ]
 [ 1.5 -0.5]]
dot is [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


### 向量的范数

向量的范数(norm)是一个将向量映射到非负值的函数，用来衡量向量的大小，直观上，向量$x$的范数用来衡量从原点到$x$的距离，$L^p$范数定义如下：
$$\parallel x\parallel_p = (\sum_i |x_i|^{p})^{\frac{1}{p}}$$ 

In [78]:
x1 = np.array([1,2,3])
L2 = np.dot(x1, x1)
L2_norm = np.sqrt(L2)
L2_norm

3.7416573867739413

In [77]:
np.linalg.norm(x1)

3.7416573867739413