# numpy

numpy的核心是一个ndarray类，该类表示多维数组，及该对象之上的操作。由于机器学习大量使用多维数组来表示数据、进行计算，因此，机器学习中会经常使用numpy。

## ndarray

- ndarray是numpy中的一个类，它表示一个多维数组，其元素的类型必须是相同的，即homogeneous multidimensional array。
- shape：维度
- dtype：类型


### 创建

In [2]:
import numpy as np

a = np.array([[1,2],[3,4]]) # 使用array函数从python的list或tuple创建
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.dtype

In [ ]:
a.shape

In [ ]:
type(a)

In [ ]:
b = np.empty(shape=(2,68,68,3),dtype=np.uint8)

In [ ]:
b

In [ ]:
c = np.array([])

In [ ]:
c

In [5]:
d = np.empty((2,2)) # 创建空数组，元素值是随机的，看当时的内存值
d

array([[6.90754766e-310, 6.90754766e-310],
       [0.00000000e+000, 0.00000000e+000]])

In [6]:
d[0] = np.array([1,2])

In [9]:
x_zeros = np.zeros((2,2)) # 创建全0数组
x_zeros

array([[0., 0.],
       [0., 0.]])

In [12]:
x_ones = np.ones((2,)) # 创建全1数组
x_ones

array([1., 1.])

In [15]:
x_arange = np.arange(0,10,2) # step序列
x_arange

array([0, 2, 4, 6, 8])

In [16]:
x_linspace = np.linspace(0,10,4) # 总数序列
x_linspace

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

### 读写元素

In [ ]:
b[1]

In [ ]:
b[1] = np.ones(shape=(68,68,3))

In [ ]:
b[1]

In [1]:
b

NameError: name 'b' is not defined

## 资料
- [官网](https://numpy.org/)